name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Create build directory
        run: mkdir build && cd build

      - name: Configure CMake
        run: cmake ..

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: ctest --output-on-failure